### ISSUE TITLE
Unable to stream camera entity or RTSP url to Google Nest Hub

### ISSUE THREAD

**Issue by moostmartijn** [AlexxIT/DashCast#11]
The screen gets stuck on the DashCast logo with 'Loading:*url*' at the bottom.

**Comment by Ronithes** [comment]
Same here

**Comment by AlexxIT** [comment]
So Hub can't connect to your server. Maybe you have wrong local IP address for your Hass. Maybe you using selfsigned certificate, maybe you have a misconfigured local network.
Only you can find the cause and fix it.

**Comment by Ronithes** [comment]
You are right,
