### ISSUE TITLE
Error in Homeassistant

### ISSUE THREAD

**Issue by pfletcher1973** [AlexxIT/DashCast#19]
Hi,  attempting to get this to work, but get teh following error when calling the Service to display on Google Nest Hub:

'DlnaDmrEntity' object has no attribute '_chromecast'

If i use Dashcast via https://stestagg.github.io/dashcast/ it works as expected and displays on the hub.

What am I doping wrong?

**Comment by AlexxIT** [comment]
You specified a non-chromecast device for this service.

**Comment by pfletcher1973** [comment]
the entity id matches that shown in the Google Cast integration. 

Executed: May 24, 2024 at 5:04:17 PM
Error: 'DlnaDmrEntity' object has no attribute '_chromecast'
Result:
params:
  domain: dash_cast
  service: load_url
  service_data:
    entity_id: media_player.kitchen_display_3
    url: http://192.168.1.48:8123/dashboard-sonos/sonos
    force: true
  target: {}
running_script: false

**Comment by AlexxIT** [comment]
DlnaDmrEntity is not a Chromecast

**Comment by pfletcher1973** [comment]
it just started working now. Similar error/info messages.
