### ISSUE TITLE
DashCast no stream

### ISSUE THREAD

**Issue by direx1** [AlexxIT/DashCast#5]
Had it working yesterday no issues with WebRTC RTSP stream. Today all I get is DashCast screen with URL at bottom. Its working ok still on 1 Chromecast but not on my other 2 which are all on the same network. I've restarted everything but same issue.

**Comment by stephenjamieson** [comment]
Same, doesn't work.

**Comment by HiTechTLS** [comment]
Having same issue, all looks good in dashcast log in HA, but all i get is the DashCast logo on the chromecast, never the site it is trying to cast.

**Comment by arashonfire** [comment]
> 

How exactly? I a;ready have signed certificates for my domain (external). If I self-sign for the internal IP, where exactly do I put them without replacing the external ones?

**Comment by AlexxIT** [comment]
Please reopen the issue if it is still relevant
